export const PHONE_DISPLAY = "+977 971 208 2949";
export const PHONE_TEL = "+9779712082949";
export const WHATSAPP_NUMBER = "9779712082949";
export const EMAIL = "info@mountainhelicoptersnepal.com";

export function waLink(message: string) {
  return `https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(message)}`;
}

export const FLIGHT_TYPES = [
  "Kathmandu to Lukla, shared seat",
  "Lukla to Kathmandu, shared seat",
  "Round trip, Kathmandu ⇄ Lukla",
  "Gorak Shep to Kathmandu, after EBC trek",
  "Everest Heli Tour: Kala Patthar landing + HEV breakfast",
  "Gokyo Lake + mountain overfly tour",
  "Private charter",
  "Not sure yet, please advise",
] as const;

/** Priority countries first, then all countries A to Z. */
export const DIAL_CODES: Array<[country: string, code: string]> = [
  ["Australia", "+61"],
  ["Canada", "+1"],
  ["Germany", "+49"],
  ["New Zealand", "+64"],
  ["United Kingdom", "+44"],
  ["United States", "+1"],
  ["Nepal", "+977"],
  ["Afghanistan", "+93"],
  ["Albania", "+355"],
  ["Algeria", "+213"],
  ["Andorra", "+376"],
  ["Angola", "+244"],
  ["Argentina", "+54"],
  ["Armenia", "+374"],
  ["Austria", "+43"],
  ["Azerbaijan", "+994"],
  ["Bahamas", "+1"],
  ["Bahrain", "+973"],
  ["Bangladesh", "+880"],
  ["Barbados", "+1"],
  ["Belarus", "+375"],
  ["Belgium", "+32"],
  ["Belize", "+501"],
  ["Benin", "+229"],
  ["Bhutan", "+975"],
  ["Bolivia", "+591"],
  ["Bosnia and Herzegovina", "+387"],
  ["Botswana", "+267"],
  ["Brazil", "+55"],
  ["Brunei", "+673"],
  ["Bulgaria", "+359"],
  ["Burkina Faso", "+226"],
  ["Burundi", "+257"],
  ["Cambodia", "+855"],
  ["Cameroon", "+237"],
  ["Cape Verde", "+238"],
  ["Chad", "+235"],
  ["Chile", "+56"],
  ["China", "+86"],
  ["Colombia", "+57"],
  ["Costa Rica", "+506"],
  ["Croatia", "+385"],
  ["Cuba", "+53"],
  ["Cyprus", "+357"],
  ["Czechia", "+420"],
  ["DR Congo", "+243"],
  ["Denmark", "+45"],
  ["Djibouti", "+253"],
  ["Dominican Republic", "+1"],
  ["Ecuador", "+593"],
  ["Egypt", "+20"],
  ["El Salvador", "+503"],
  ["Estonia", "+372"],
  ["Eswatini", "+268"],
  ["Ethiopia", "+251"],
  ["Fiji", "+679"],
  ["Finland", "+358"],
  ["France", "+33"],
  ["Gabon", "+241"],
  ["Gambia", "+220"],
  ["Georgia", "+995"],
  ["Ghana", "+233"],
  ["Greece", "+30"],
  ["Guatemala", "+502"],
  ["Guinea", "+224"],
  ["Guyana", "+592"],
  ["Haiti", "+509"],
  ["Honduras", "+504"],
  ["Hong Kong", "+852"],
  ["Hungary", "+36"],
  ["Iceland", "+354"],
  ["India", "+91"],
  ["Indonesia", "+62"],
  ["Iran", "+98"],
  ["Iraq", "+964"],
  ["Ireland", "+353"],
  ["Israel", "+972"],
  ["Italy", "+39"],
  ["Ivory Coast", "+225"],
  ["Jamaica", "+1"],
  ["Japan", "+81"],
  ["Jordan", "+962"],
  ["Kazakhstan", "+7"],
  ["Kenya", "+254"],
  ["Kuwait", "+965"],
  ["Kyrgyzstan", "+996"],
  ["Laos", "+856"],
  ["Latvia", "+371"],
  ["Lebanon", "+961"],
  ["Lesotho", "+266"],
  ["Liberia", "+231"],
  ["Libya", "+218"],
  ["Liechtenstein", "+423"],
  ["Lithuania", "+370"],
  ["Luxembourg", "+352"],
  ["Macau", "+853"],
  ["Madagascar", "+261"],
  ["Malawi", "+265"],
  ["Malaysia", "+60"],
  ["Maldives", "+960"],
  ["Mali", "+223"],
  ["Malta", "+356"],
  ["Mauritania", "+222"],
  ["Mauritius", "+230"],
  ["Mexico", "+52"],
  ["Moldova", "+373"],
  ["Monaco", "+377"],
  ["Mongolia", "+976"],
  ["Montenegro", "+382"],
  ["Morocco", "+212"],
  ["Mozambique", "+258"],
  ["Myanmar", "+95"],
  ["Namibia", "+264"],
  ["Netherlands", "+31"],
  ["Nicaragua", "+505"],
  ["Niger", "+227"],
  ["Nigeria", "+234"],
  ["North Macedonia", "+389"],
  ["Norway", "+47"],
  ["Oman", "+968"],
  ["Pakistan", "+92"],
  ["Panama", "+507"],
  ["Papua New Guinea", "+675"],
  ["Paraguay", "+595"],
  ["Peru", "+51"],
  ["Philippines", "+63"],
  ["Poland", "+48"],
  ["Portugal", "+351"],
  ["Qatar", "+974"],
  ["Romania", "+40"],
  ["Russia", "+7"],
  ["Rwanda", "+250"],
  ["Saudi Arabia", "+966"],
  ["Senegal", "+221"],
  ["Serbia", "+381"],
  ["Seychelles", "+248"],
  ["Sierra Leone", "+232"],
  ["Singapore", "+65"],
  ["Slovakia", "+421"],
  ["Slovenia", "+386"],
  ["Somalia", "+252"],
  ["South Africa", "+27"],
  ["South Korea", "+82"],
  ["South Sudan", "+211"],
  ["Spain", "+34"],
  ["Sri Lanka", "+94"],
  ["Sudan", "+249"],
  ["Suriname", "+597"],
  ["Sweden", "+46"],
  ["Switzerland", "+41"],
  ["Syria", "+963"],
  ["Taiwan", "+886"],
  ["Tajikistan", "+992"],
  ["Tanzania", "+255"],
  ["Thailand", "+66"],
  ["Togo", "+228"],
  ["Trinidad and Tobago", "+1"],
  ["Tunisia", "+216"],
  ["Turkey", "+90"],
  ["Turkmenistan", "+993"],
  ["Uganda", "+256"],
  ["Ukraine", "+380"],
  ["United Arab Emirates", "+971"],
  ["Uruguay", "+598"],
  ["Uzbekistan", "+998"],
  ["Venezuela", "+58"],
  ["Vietnam", "+84"],
  ["Yemen", "+967"],
  ["Zambia", "+260"],
  ["Zimbabwe", "+263"],
];

export const FAQS = [
  {
    question: "Do you really depart every day?",
    answer:
      "Yes. Departures are scheduled every day in both directions, timed to the morning weather window. Mountain weather has the final word, and if a window closes you move to the next one at no charge.",
  },
  {
    question: "Can you pick me up from Gorak Shep after Base Camp?",
    answer:
      "Yes. Message us from the trail a day ahead and we schedule a morning pickup from Gorak Shep at 5,164 m. At that altitude the helicopter carries fewer passengers per lift, so groups may shuttle via Pheriche or Lukla before flying on to Kathmandu. You are back the same day.",
  },
  {
    question: "How much luggage can I bring?",
    answer:
      "10 kg per person on shared flights, including your day pack. Extra trekking baggage can often be arranged in advance or sent on a cargo flight. Tell us at booking and we will plan it.",
  },
  {
    question: "Is the Kala Patthar landing safe at that altitude?",
    answer:
      "Landings above 5,000 m are kept deliberately short, typically under 10 minutes, and the crew briefs you before landing. The tour then descends to Hotel Everest View at 3,880 m for a relaxed breakfast.",
  },
  {
    question: "What happens if weather cancels my flight or tour?",
    answer:
      "You move to the next available window at no charge, or receive a refund per the booking terms shared in writing before you pay. Safety decides the schedule, always.",
  },
  {
    question: "How and when do I pay?",
    answer:
      "A deposit confirms your seat and the balance is settled before departure. We accept international cards and bank transfer, with full terms shared in writing before any payment.",
  },
] as const;
